export type Country = {
  name: string;
  code: string;
  slug: string;
};

export const COUNTRIES: Country[] = [
  { name: 'Afghanistan', code: 'af', slug: 'afghanistan' },
  { name: 'Albania', code: 'al', slug: 'albania' },
  { name: 'Algeria', code: 'dz', slug: 'algeria' },
  { name: 'Andorra', code: 'ad', slug: 'andorra' },
  { name: 'Angola', code: 'ao', slug: 'angola' },
  { name: 'Antigua and Barbuda', code: 'ag', slug: 'antigua-and-barbuda' },
  { name: 'Argentina', code: 'ar', slug: 'argentina' },
  { name: 'Armenia', code: 'am', slug: 'armenia' },
  { name: 'Australia', code: 'au', slug: 'australia' },
  { name: 'Austria', code: 'at', slug: 'austria' },
  { name: 'Azerbaijan', code: 'az', slug: 'azerbaijan' },
  { name: 'Bahamas', code: 'bs', slug: 'bahamas' },
  { name: 'Bahrain', code: 'bh', slug: 'bahrain' },
  { name: 'Bangladesh', code: 'bd', slug: 'bangladesh' },
  { name: 'Barbados', code: 'bb', slug: 'barbados' },
  { name: 'Belarus', code: 'by', slug: 'belarus' },
  { name: 'Belgium', code: 'be', slug: 'belgium' },
  { name: 'Belize', code: 'bz', slug: 'belize' },
  { name: 'Benin', code: 'bj', slug: 'benin' },
  { name: 'Bhutan', code: 'bt', slug: 'bhutan' },
  { name: 'Bolivia', code: 'bo', slug: 'bolivia' },
  { name: 'Bosnia and Herzegovina', code: 'ba', slug: 'bosnia-and-herzegovina' },
  { name: 'Botswana', code: 'bw', slug: 'botswana' },
  { name: 'Brazil', code: 'br', slug: 'brazil' },
  { name: 'Brunei', code: 'bn', slug: 'brunei' },
  { name: 'Bulgaria', code: 'bg', slug: 'bulgaria' },
  { name: 'Burkina Faso', code: 'bf', slug: 'burkina-faso' },
  { name: 'Burundi', code: 'bi', slug: 'burundi' },
  { name: 'Cabo Verde', code: 'cv', slug: 'cabo-verde' },
  { name: 'Cambodia', code: 'kh', slug: 'cambodia' },
  { name: 'Cameroon', code: 'cm', slug: 'cameroon' },
  { name: 'Canada', code: 'ca', slug: 'canada' },
  { name: 'Central African Republic', code: 'cf', slug: 'central-african-republic' },
  { name: 'Chad', code: 'td', slug: 'chad' },
  { name: 'Chile', code: 'cl', slug: 'chile' },
  { name: 'China', code: 'cn', slug: 'china' },
  { name: 'Colombia', code: 'co', slug: 'colombia' },
  { name: 'Comoros', code: 'km', slug: 'comoros' },
  { name: 'Congo (DRC)', code: 'cd', slug: 'democratic-republic-of-the-congo' },
  { name: 'Congo (Republic)', code: 'cg', slug: 'republic-of-the-congo' },
  { name: 'Costa Rica', code: 'cr', slug: 'costa-rica' },
  { name: 'Croatia', code: 'hr', slug: 'croatia' },
  { name: 'Cuba', code: 'cu', slug: 'cuba' },
  { name: 'Cyprus', code: 'cy', slug: 'cyprus' },
  { name: 'Czech Republic', code: 'cz', slug: 'czech-republic' },
  { name: 'Denmark', code: 'dk', slug: 'denmark' },
  { name: 'Djibouti', code: 'dj', slug: 'djibouti' },
  { name: 'Dominica', code: 'dm', slug: 'dominica' },
  { name: 'Dominican Republic', code: 'do', slug: 'dominican-republic' },
  { name: 'Ecuador', code: 'ec', slug: 'ecuador' },
  { name: 'Egypt', code: 'eg', slug: 'egypt' },
  { name: 'El Salvador', code: 'sv', slug: 'el-salvador' },
  { name: 'Equatorial Guinea', code: 'gq', slug: 'equatorial-guinea' },
  { name: 'Eritrea', code: 'er', slug: 'eritrea' },
  { name: 'Estonia', code: 'ee', slug: 'estonia' },
  { name: 'Eswatini', code: 'sz', slug: 'eswatini' },
  { name: 'Ethiopia', code: 'et', slug: 'ethiopia' },
  { name: 'Fiji', code: 'fj', slug: 'fiji' },
  { name: 'Finland', code: 'fi', slug: 'finland' },
  { name: 'France', code: 'fr', slug: 'france' },
  { name: 'Gabon', code: 'ga', slug: 'gabon' },
  { name: 'Gambia', code: 'gm', slug: 'gambia' },
  { name: 'Georgia', code: 'ge', slug: 'georgia' },
  { name: 'Germany', code: 'de', slug: 'germany' },
  { name: 'Ghana', code: 'gh', slug: 'ghana' },
  { name: 'Greece', code: 'gr', slug: 'greece' },
  { name: 'Grenada', code: 'gd', slug: 'grenada' },
  { name: 'Guatemala', code: 'gt', slug: 'guatemala' },
  { name: 'Guinea', code: 'gn', slug: 'guinea' },
  { name: 'Guinea-Bissau', code: 'gw', slug: 'guinea-bissau' },
  { name: 'Guyana', code: 'gy', slug: 'guyana' },
  { name: 'Haiti', code: 'ht', slug: 'haiti' },
  { name: 'Honduras', code: 'hn', slug: 'honduras' },
  { name: 'Hungary', code: 'hu', slug: 'hungary' },
  { name: 'Iceland', code: 'is', slug: 'iceland' },
  { name: 'India', code: 'in', slug: 'india' },
  { name: 'Indonesia', code: 'id', slug: 'indonesia' },
  { name: 'Iran', code: 'ir', slug: 'iran' },
  { name: 'Iraq', code: 'iq', slug: 'iraq' },
  { name: 'Ireland', code: 'ie', slug: 'ireland' },
  { name: 'Israel', code: 'il', slug: 'israel' },
  { name: 'Italy', code: 'it', slug: 'italy' },
  { name: 'Ivory Coast', code: 'ci', slug: 'ivory-coast' },
  { name: 'Jamaica', code: 'jm', slug: 'jamaica' },
  { name: 'Japan', code: 'jp', slug: 'japan' },
  { name: 'Jordan', code: 'jo', slug: 'jordan' },
  { name: 'Kazakhstan', code: 'kz', slug: 'kazakhstan' },
  { name: 'Kenya', code: 'ke', slug: 'kenya' },
  { name: 'Kiribati', code: 'ki', slug: 'kiribati' },
  { name: 'Kosovo', code: 'xk', slug: 'kosovo' },
  { name: 'Kuwait', code: 'kw', slug: 'kuwait' },
  { name: 'Kyrgyzstan', code: 'kg', slug: 'kyrgyzstan' },
  { name: 'Laos', code: 'la', slug: 'laos' },
  { name: 'Latvia', code: 'lv', slug: 'latvia' },
  { name: 'Lebanon', code: 'lb', slug: 'lebanon' },
  { name: 'Lesotho', code: 'ls', slug: 'lesotho' },
  { name: 'Liberia', code: 'lr', slug: 'liberia' },
  { name: 'Libya', code: 'ly', slug: 'libya' },
  { name: 'Liechtenstein', code: 'li', slug: 'liechtenstein' },
  { name: 'Lithuania', code: 'lt', slug: 'lithuania' },
  { name: 'Luxembourg', code: 'lu', slug: 'luxembourg' },
  { name: 'Madagascar', code: 'mg', slug: 'madagascar' },
  { name: 'Malawi', code: 'mw', slug: 'malawi' },
  { name: 'Malaysia', code: 'my', slug: 'malaysia' },
  { name: 'Maldives', code: 'mv', slug: 'maldives' },
  { name: 'Mali', code: 'ml', slug: 'mali' },
  { name: 'Malta', code: 'mt', slug: 'malta' },
  { name: 'Marshall Islands', code: 'mh', slug: 'marshall-islands' },
  { name: 'Mauritania', code: 'mr', slug: 'mauritania' },
  { name: 'Mauritius', code: 'mu', slug: 'mauritius' },
  { name: 'Mexico', code: 'mx', slug: 'mexico' },
  { name: 'Micronesia', code: 'fm', slug: 'micronesia' },
  { name: 'Moldova', code: 'md', slug: 'moldova' },
  { name: 'Monaco', code: 'mc', slug: 'monaco' },
  { name: 'Mongolia', code: 'mn', slug: 'mongolia' },
  { name: 'Montenegro', code: 'me', slug: 'montenegro' },
  { name: 'Morocco', code: 'ma', slug: 'morocco' },
  { name: 'Mozambique', code: 'mz', slug: 'mozambique' },
  { name: 'Myanmar', code: 'mm', slug: 'myanmar' },
  { name: 'Namibia', code: 'na', slug: 'namibia' },
  { name: 'Nauru', code: 'nr', slug: 'nauru' },
  { name: 'Nepal', code: 'np', slug: 'nepal' },
  { name: 'Netherlands', code: 'nl', slug: 'netherlands' },
  { name: 'New Zealand', code: 'nz', slug: 'new-zealand' },
  { name: 'Nicaragua', code: 'ni', slug: 'nicaragua' },
  { name: 'Niger', code: 'ne', slug: 'niger' },
  { name: 'Nigeria', code: 'ng', slug: 'nigeria' },
  { name: 'North Korea', code: 'kp', slug: 'north-korea' },
  { name: 'North Macedonia', code: 'mk', slug: 'north-macedonia' },
  { name: 'Norway', code: 'no', slug: 'norway' },
  { name: 'Oman', code: 'om', slug: 'oman' },
  { name: 'Pakistan', code: 'pk', slug: 'pakistan' },
  { name: 'Palau', code: 'pw', slug: 'palau' },
  { name: 'Palestine', code: 'ps', slug: 'palestine' },
  { name: 'Panama', code: 'pa', slug: 'panama' },
  { name: 'Papua New Guinea', code: 'pg', slug: 'papua-new-guinea' },
  { name: 'Paraguay', code: 'py', slug: 'paraguay' },
  { name: 'Peru', code: 'pe', slug: 'peru' },
  { name: 'Philippines', code: 'ph', slug: 'philippines' },
  { name: 'Poland', code: 'pl', slug: 'poland' },
  { name: 'Portugal', code: 'pt', slug: 'portugal' },
  { name: 'Qatar', code: 'qa', slug: 'qatar' },
  { name: 'Romania', code: 'ro', slug: 'romania' },
  { name: 'Russia', code: 'ru', slug: 'russia' },
  { name: 'Rwanda', code: 'rw', slug: 'rwanda' },
  { name: 'Saint Kitts and Nevis', code: 'kn', slug: 'saint-kitts-and-nevis' },
  { name: 'Saint Lucia', code: 'lc', slug: 'saint-lucia' },
  { name: 'Saint Vincent and the Grenadines', code: 'vc', slug: 'saint-vincent-and-the-grenadines' },
  { name: 'Samoa', code: 'ws', slug: 'samoa' },
  { name: 'San Marino', code: 'sm', slug: 'san-marino' },
  { name: 'Sao Tome and Principe', code: 'st', slug: 'sao-tome-and-principe' },
  { name: 'Saudi Arabia', code: 'sa', slug: 'saudi-arabia' },
  { name: 'Senegal', code: 'sn', slug: 'senegal' },
  { name: 'Serbia', code: 'rs', slug: 'serbia' },
  { name: 'Seychelles', code: 'sc', slug: 'seychelles' },
  { name: 'Sierra Leone', code: 'sl', slug: 'sierra-leone' },
  { name: 'Singapore', code: 'sg', slug: 'singapore' },
  { name: 'Slovakia', code: 'sk', slug: 'slovakia' },
  { name: 'Slovenia', code: 'si', slug: 'slovenia' },
  { name: 'Solomon Islands', code: 'sb', slug: 'solomon-islands' },
  { name: 'Somalia', code: 'so', slug: 'somalia' },
  { name: 'South Africa', code: 'za', slug: 'south-africa' },
  { name: 'South Korea', code: 'kr', slug: 'south-korea' },
  { name: 'South Sudan', code: 'ss', slug: 'south-sudan' },
  { name: 'Spain', code: 'es', slug: 'spain' },
  { name: 'Sri Lanka', code: 'lk', slug: 'sri-lanka' },
  { name: 'Sudan', code: 'sd', slug: 'sudan' },
  { name: 'Suriname', code: 'sr', slug: 'suriname' },
  { name: 'Sweden', code: 'se', slug: 'sweden' },
  { name: 'Switzerland', code: 'ch', slug: 'switzerland' },
  { name: 'Syria', code: 'sy', slug: 'syria' },
  { name: 'Taiwan', code: 'tw', slug: 'taiwan' },
  { name: 'Tajikistan', code: 'tj', slug: 'tajikistan' },
  { name: 'Tanzania', code: 'tz', slug: 'tanzania' },
  { name: 'Thailand', code: 'th', slug: 'thailand' },
  { name: 'Timor-Leste', code: 'tl', slug: 'timor-leste' },
  { name: 'Togo', code: 'tg', slug: 'togo' },
  { name: 'Tonga', code: 'to', slug: 'tonga' },
  { name: 'Trinidad and Tobago', code: 'tt', slug: 'trinidad-and-tobago' },
  { name: 'Tunisia', code: 'tn', slug: 'tunisia' },
  { name: 'Turkey', code: 'tr', slug: 'turkey' },
  { name: 'Turkmenistan', code: 'tm', slug: 'turkmenistan' },
  { name: 'Tuvalu', code: 'tv', slug: 'tuvalu' },
  { name: 'Uganda', code: 'ug', slug: 'uganda' },
  { name: 'Ukraine', code: 'ua', slug: 'ukraine' },
  { name: 'United Arab Emirates', code: 'ae', slug: 'united-arab-emirates' },
  { name: 'United Kingdom', code: 'gb', slug: 'united-kingdom' },
  { name: 'United States', code: 'us', slug: 'united-states' },
  { name: 'Uruguay', code: 'uy', slug: 'uruguay' },
  { name: 'Uzbekistan', code: 'uz', slug: 'uzbekistan' },
  { name: 'Vanuatu', code: 'vu', slug: 'vanuatu' },
  { name: 'Vatican City', code: 'va', slug: 'vatican-city' },
  { name: 'Venezuela', code: 've', slug: 'venezuela' },
  { name: 'Vietnam', code: 'vn', slug: 'vietnam' },
  { name: 'Yemen', code: 'ye', slug: 'yemen' },
  { name: 'Zambia', code: 'zm', slug: 'zambia' },
  { name: 'Zimbabwe', code: 'zw', slug: 'zimbabwe' },
];
