export interface CountryFlag {
  name: string;
  isoCode: string;
  flagUrl: string;
}

export function getFlagUrl(isoCode: string): string {
  return `https://flagcdn.com/w320/${isoCode.toLowerCase()}.png`;
}

export function searchFlags(query: string): CountryFlag[] {
  if (!query || query.length < 1) return [];
  const q = query.toLowerCase();
  return ALL_COUNTRIES.filter((c) => c.name.toLowerCase().includes(q)).slice(0, 15);
}

export const ALL_COUNTRIES: CountryFlag[] = [
  { name: 'Afghanistan', isoCode: 'af', flagUrl: getFlagUrl('af') },
  { name: 'Albania', isoCode: 'al', flagUrl: getFlagUrl('al') },
  { name: 'Algeria', isoCode: 'dz', flagUrl: getFlagUrl('dz') },
  { name: 'Argentina', isoCode: 'ar', flagUrl: getFlagUrl('ar') },
  { name: 'Armenia', isoCode: 'am', flagUrl: getFlagUrl('am') },
  { name: 'Australia', isoCode: 'au', flagUrl: getFlagUrl('au') },
  { name: 'Austria', isoCode: 'at', flagUrl: getFlagUrl('at') },
  { name: 'Azerbaijan', isoCode: 'az', flagUrl: getFlagUrl('az') },
  { name: 'Bahrain', isoCode: 'bh', flagUrl: getFlagUrl('bh') },
  { name: 'Bangladesh', isoCode: 'bd', flagUrl: getFlagUrl('bd') },
  { name: 'Belarus', isoCode: 'by', flagUrl: getFlagUrl('by') },
  { name: 'Belgium', isoCode: 'be', flagUrl: getFlagUrl('be') },
  { name: 'Bolivia', isoCode: 'bo', flagUrl: getFlagUrl('bo') },
  { name: 'Bosnia and Herzegovina', isoCode: 'ba', flagUrl: getFlagUrl('ba') },
  { name: 'Brazil', isoCode: 'br', flagUrl: getFlagUrl('br') },
  { name: 'Bulgaria', isoCode: 'bg', flagUrl: getFlagUrl('bg') },
  { name: 'Cambodia', isoCode: 'kh', flagUrl: getFlagUrl('kh') },
  { name: 'Cameroon', isoCode: 'cm', flagUrl: getFlagUrl('cm') },
  { name: 'Canada', isoCode: 'ca', flagUrl: getFlagUrl('ca') },
  { name: 'Chile', isoCode: 'cl', flagUrl: getFlagUrl('cl') },
  { name: 'China', isoCode: 'cn', flagUrl: getFlagUrl('cn') },
  { name: 'Colombia', isoCode: 'co', flagUrl: getFlagUrl('co') },
  { name: 'Croatia', isoCode: 'hr', flagUrl: getFlagUrl('hr') },
  { name: 'Cuba', isoCode: 'cu', flagUrl: getFlagUrl('cu') },
  { name: 'Czech Republic', isoCode: 'cz', flagUrl: getFlagUrl('cz') },
  { name: 'Denmark', isoCode: 'dk', flagUrl: getFlagUrl('dk') },
  { name: 'Ecuador', isoCode: 'ec', flagUrl: getFlagUrl('ec') },
  { name: 'Egypt', isoCode: 'eg', flagUrl: getFlagUrl('eg') },
  { name: 'England', isoCode: 'gb-eng', flagUrl: getFlagUrl('gb-eng') },
  { name: 'Ethiopia', isoCode: 'et', flagUrl: getFlagUrl('et') },
  { name: 'Finland', isoCode: 'fi', flagUrl: getFlagUrl('fi') },
  { name: 'France', isoCode: 'fr', flagUrl: getFlagUrl('fr') },
  { name: 'Georgia', isoCode: 'ge', flagUrl: getFlagUrl('ge') },
  { name: 'Germany', isoCode: 'de', flagUrl: getFlagUrl('de') },
  { name: 'Ghana', isoCode: 'gh', flagUrl: getFlagUrl('gh') },
  { name: 'Greece', isoCode: 'gr', flagUrl: getFlagUrl('gr') },
  { name: 'Hungary', isoCode: 'hu', flagUrl: getFlagUrl('hu') },
  { name: 'India', isoCode: 'in', flagUrl: getFlagUrl('in') },
  { name: 'Indonesia', isoCode: 'id', flagUrl: getFlagUrl('id') },
  { name: 'Iran', isoCode: 'ir', flagUrl: getFlagUrl('ir') },
  { name: 'Iraq', isoCode: 'iq', flagUrl: getFlagUrl('iq') },
  { name: 'Ireland', isoCode: 'ie', flagUrl: getFlagUrl('ie') },
  { name: 'Italy', isoCode: 'it', flagUrl: getFlagUrl('it') },
  { name: 'Japan', isoCode: 'jp', flagUrl: getFlagUrl('jp') },
  { name: 'Jordan', isoCode: 'jo', flagUrl: getFlagUrl('jo') },
  { name: 'Kazakhstan', isoCode: 'kz', flagUrl: getFlagUrl('kz') },
  { name: 'Kenya', isoCode: 'ke', flagUrl: getFlagUrl('ke') },
  { name: 'Kuwait', isoCode: 'kw', flagUrl: getFlagUrl('kw') },
  { name: 'Kyrgyzstan', isoCode: 'kg', flagUrl: getFlagUrl('kg') },
  { name: 'Latvia', isoCode: 'lv', flagUrl: getFlagUrl('lv') },
  { name: 'Lebanon', isoCode: 'lb', flagUrl: getFlagUrl('lb') },
  { name: 'Libya', isoCode: 'ly', flagUrl: getFlagUrl('ly') },
  { name: 'Lithuania', isoCode: 'lt', flagUrl: getFlagUrl('lt') },
  { name: 'Malaysia', isoCode: 'my', flagUrl: getFlagUrl('my') },
  { name: 'Mexico', isoCode: 'mx', flagUrl: getFlagUrl('mx') },
  { name: 'Moldova', isoCode: 'md', flagUrl: getFlagUrl('md') },
  { name: 'Mongolia', isoCode: 'mn', flagUrl: getFlagUrl('mn') },
  { name: 'Montenegro', isoCode: 'me', flagUrl: getFlagUrl('me') },
  { name: 'Morocco', isoCode: 'ma', flagUrl: getFlagUrl('ma') },
  { name: 'Myanmar', isoCode: 'mm', flagUrl: getFlagUrl('mm') },
  { name: 'Netherlands', isoCode: 'nl', flagUrl: getFlagUrl('nl') },
  { name: 'New Zealand', isoCode: 'nz', flagUrl: getFlagUrl('nz') },
  { name: 'Nigeria', isoCode: 'ng', flagUrl: getFlagUrl('ng') },
  { name: 'North Korea', isoCode: 'kp', flagUrl: getFlagUrl('kp') },
  { name: 'Norway', isoCode: 'no', flagUrl: getFlagUrl('no') },
  { name: 'Oman', isoCode: 'om', flagUrl: getFlagUrl('om') },
  { name: 'Pakistan', isoCode: 'pk', flagUrl: getFlagUrl('pk') },
  { name: 'Palestine', isoCode: 'ps', flagUrl: getFlagUrl('ps') },
  { name: 'Panama', isoCode: 'pa', flagUrl: getFlagUrl('pa') },
  { name: 'Paraguay', isoCode: 'py', flagUrl: getFlagUrl('py') },
  { name: 'Peru', isoCode: 'pe', flagUrl: getFlagUrl('pe') },
  { name: 'Philippines', isoCode: 'ph', flagUrl: getFlagUrl('ph') },
  { name: 'Poland', isoCode: 'pl', flagUrl: getFlagUrl('pl') },
  { name: 'Portugal', isoCode: 'pt', flagUrl: getFlagUrl('pt') },
  { name: 'Qatar', isoCode: 'qa', flagUrl: getFlagUrl('qa') },
  { name: 'Romania', isoCode: 'ro', flagUrl: getFlagUrl('ro') },
  { name: 'Russia', isoCode: 'ru', flagUrl: getFlagUrl('ru') },
  { name: 'Saudi Arabia', isoCode: 'sa', flagUrl: getFlagUrl('sa') },
  { name: 'Scotland', isoCode: 'gb-sct', flagUrl: getFlagUrl('gb-sct') },
  { name: 'Senegal', isoCode: 'sn', flagUrl: getFlagUrl('sn') },
  { name: 'Serbia', isoCode: 'rs', flagUrl: getFlagUrl('rs') },
  { name: 'Slovakia', isoCode: 'sk', flagUrl: getFlagUrl('sk') },
  { name: 'Slovenia', isoCode: 'si', flagUrl: getFlagUrl('si') },
  { name: 'Somalia', isoCode: 'so', flagUrl: getFlagUrl('so') },
  { name: 'South Africa', isoCode: 'za', flagUrl: getFlagUrl('za') },
  { name: 'South Korea', isoCode: 'kr', flagUrl: getFlagUrl('kr') },
  { name: 'Spain', isoCode: 'es', flagUrl: getFlagUrl('es') },
  { name: 'Sweden', isoCode: 'se', flagUrl: getFlagUrl('se') },
  { name: 'Switzerland', isoCode: 'ch', flagUrl: getFlagUrl('ch') },
  { name: 'Syria', isoCode: 'sy', flagUrl: getFlagUrl('sy') },
  { name: 'Tajikistan', isoCode: 'tj', flagUrl: getFlagUrl('tj') },
  { name: 'Thailand', isoCode: 'th', flagUrl: getFlagUrl('th') },
  { name: 'Tunisia', isoCode: 'tn', flagUrl: getFlagUrl('tn') },
  { name: 'Turkey', isoCode: 'tr', flagUrl: getFlagUrl('tr') },
  { name: 'Turkmenistan', isoCode: 'tm', flagUrl: getFlagUrl('tm') },
  { name: 'Uganda', isoCode: 'ug', flagUrl: getFlagUrl('ug') },
  { name: 'Ukraine', isoCode: 'ua', flagUrl: getFlagUrl('ua') },
  { name: 'United Arab Emirates', isoCode: 'ae', flagUrl: getFlagUrl('ae') },
  { name: 'United Kingdom', isoCode: 'gb', flagUrl: getFlagUrl('gb') },
  { name: 'United States', isoCode: 'us', flagUrl: getFlagUrl('us') },
  { name: 'Uruguay', isoCode: 'uy', flagUrl: getFlagUrl('uy') },
  { name: 'Uzbekistan', isoCode: 'uz', flagUrl: getFlagUrl('uz') },
  { name: 'Venezuela', isoCode: 've', flagUrl: getFlagUrl('ve') },
  { name: 'Vietnam', isoCode: 'vn', flagUrl: getFlagUrl('vn') },
  { name: 'Wales', isoCode: 'gb-wls', flagUrl: getFlagUrl('gb-wls') },
  { name: 'Yemen', isoCode: 'ye', flagUrl: getFlagUrl('ye') },
  { name: 'Zambia', isoCode: 'zm', flagUrl: getFlagUrl('zm') },
  { name: 'Zimbabwe', isoCode: 'zw', flagUrl: getFlagUrl('zw') },
];
