export type CanonicalCountry = {
  name: string;
  code: string;
  slug: string;
};

export const CANONICAL_COUNTRIES: CanonicalCountry[] = [
  ['Afghanistan', 'af', 'afghanistan'],
  ['Albania', 'al', 'albania'],
  ['Algeria', 'dz', 'algeria'],
  ['Andorra', 'ad', 'andorra'],
  ['Angola', 'ao', 'angola'],
  ['Antigua and Barbuda', 'ag', 'antigua-and-barbuda'],
  ['Argentina', 'ar', 'argentina'],
  ['Armenia', 'am', 'armenia'],
  ['Australia', 'au', 'australia'],
  ['Austria', 'at', 'austria'],
  ['Azerbaijan', 'az', 'azerbaijan'],
  ['Bahamas', 'bs', 'bahamas'],
  ['Bahrain', 'bh', 'bahrain'],
  ['Bangladesh', 'bd', 'bangladesh'],
  ['Barbados', 'bb', 'barbados'],
  ['Belarus', 'by', 'belarus'],
  ['Belgium', 'be', 'belgium'],
  ['Belize', 'bz', 'belize'],
  ['Benin', 'bj', 'benin'],
  ['Bhutan', 'bt', 'bhutan'],
  ['Bolivia', 'bo', 'bolivia'],
  ['Bosnia and Herzegovina', 'ba', 'bosnia-and-herzegovina'],
  ['Botswana', 'bw', 'botswana'],
  ['Brazil', 'br', 'brazil'],
  ['Brunei', 'bn', 'brunei'],
  ['Bulgaria', 'bg', 'bulgaria'],
  ['Burkina Faso', 'bf', 'burkina-faso'],
  ['Burundi', 'bi', 'burundi'],
  ['Cabo Verde', 'cv', 'cabo-verde'],
  ['Cambodia', 'kh', 'cambodia'],
  ['Cameroon', 'cm', 'cameroon'],
  ['Canada', 'ca', 'canada'],
  ['Central African Republic', 'cf', 'central-african-republic'],
  ['Chad', 'td', 'chad'],
  ['Chile', 'cl', 'chile'],
  ['China', 'cn', 'china'],
  ['Colombia', 'co', 'colombia'],
  ['Comoros', 'km', 'comoros'],
  ['Congo (DRC)', 'cd', 'democratic-republic-of-the-congo'],
  ['Congo (Republic)', 'cg', 'republic-of-the-congo'],
  ['Costa Rica', 'cr', 'costa-rica'],
  ['Croatia', 'hr', 'croatia'],
  ['Cuba', 'cu', 'cuba'],
  ['Cyprus', 'cy', 'cyprus'],
  ['Czech Republic', 'cz', 'czech-republic'],
  ['Denmark', 'dk', 'denmark'],
  ['Djibouti', 'dj', 'djibouti'],
  ['Dominica', 'dm', 'dominica'],
  ['Dominican Republic', 'do', 'dominican-republic'],
  ['Ecuador', 'ec', 'ecuador'],
  ['Egypt', 'eg', 'egypt'],
  ['El Salvador', 'sv', 'el-salvador'],
  ['Equatorial Guinea', 'gq', 'equatorial-guinea'],
  ['Eritrea', 'er', 'eritrea'],
  ['Estonia', 'ee', 'estonia'],
  ['Eswatini', 'sz', 'eswatini'],
  ['Ethiopia', 'et', 'ethiopia'],
  ['Fiji', 'fj', 'fiji'],
  ['Finland', 'fi', 'finland'],
  ['France', 'fr', 'france'],
  ['Gabon', 'ga', 'gabon'],
  ['Gambia', 'gm', 'gambia'],
  ['Georgia', 'ge', 'georgia'],
  ['Germany', 'de', 'germany'],
  ['Ghana', 'gh', 'ghana'],
  ['Greece', 'gr', 'greece'],
  ['Grenada', 'gd', 'grenada'],
  ['Guatemala', 'gt', 'guatemala'],
  ['Guinea', 'gn', 'guinea'],
  ['Guinea-Bissau', 'gw', 'guinea-bissau'],
  ['Guyana', 'gy', 'guyana'],
  ['Haiti', 'ht', 'haiti'],
  ['Honduras', 'hn', 'honduras'],
  ['Hungary', 'hu', 'hungary'],
  ['Iceland', 'is', 'iceland'],
  ['India', 'in', 'india'],
  ['Indonesia', 'id', 'indonesia'],
  ['Iran', 'ir', 'iran'],
  ['Iraq', 'iq', 'iraq'],
  ['Ireland', 'ie', 'ireland'],
  ['Israel', 'il', 'israel'],
  ['Italy', 'it', 'italy'],
  ['Ivory Coast', 'ci', 'ivory-coast'],
  ['Jamaica', 'jm', 'jamaica'],
  ['Japan', 'jp', 'japan'],
  ['Jordan', 'jo', 'jordan'],
  ['Kazakhstan', 'kz', 'kazakhstan'],
  ['Kenya', 'ke', 'kenya'],
  ['Kiribati', 'ki', 'kiribati'],
  ['Kosovo', 'xk', 'kosovo'],
  ['Kuwait', 'kw', 'kuwait'],
  ['Kyrgyzstan', 'kg', 'kyrgyzstan'],
  ['Laos', 'la', 'laos'],
  ['Latvia', 'lv', 'latvia'],
  ['Lebanon', 'lb', 'lebanon'],
  ['Lesotho', 'ls', 'lesotho'],
  ['Liberia', 'lr', 'liberia'],
  ['Libya', 'ly', 'libya'],
  ['Liechtenstein', 'li', 'liechtenstein'],
  ['Lithuania', 'lt', 'lithuania'],
  ['Luxembourg', 'lu', 'luxembourg'],
  ['Madagascar', 'mg', 'madagascar'],
  ['Malawi', 'mw', 'malawi'],
  ['Malaysia', 'my', 'malaysia'],
  ['Maldives', 'mv', 'maldives'],
  ['Mali', 'ml', 'mali'],
  ['Malta', 'mt', 'malta'],
  ['Marshall Islands', 'mh', 'marshall-islands'],
  ['Mauritania', 'mr', 'mauritania'],
  ['Mauritius', 'mu', 'mauritius'],
  ['Mexico', 'mx', 'mexico'],
  ['Micronesia', 'fm', 'micronesia'],
  ['Moldova', 'md', 'moldova'],
  ['Monaco', 'mc', 'monaco'],
  ['Mongolia', 'mn', 'mongolia'],
  ['Montenegro', 'me', 'montenegro'],
  ['Morocco', 'ma', 'morocco'],
  ['Mozambique', 'mz', 'mozambique'],
  ['Myanmar', 'mm', 'myanmar'],
  ['Namibia', 'na', 'namibia'],
  ['Nauru', 'nr', 'nauru'],
  ['Nepal', 'np', 'nepal'],
  ['Netherlands', 'nl', 'netherlands'],
  ['New Zealand', 'nz', 'new-zealand'],
  ['Nicaragua', 'ni', 'nicaragua'],
  ['Niger', 'ne', 'niger'],
  ['Nigeria', 'ng', 'nigeria'],
  ['North Korea', 'kp', 'north-korea'],
  ['North Macedonia', 'mk', 'north-macedonia'],
  ['Norway', 'no', 'norway'],
  ['Oman', 'om', 'oman'],
  ['Pakistan', 'pk', 'pakistan'],
  ['Palau', 'pw', 'palau'],
  ['Palestine', 'ps', 'palestine'],
  ['Panama', 'pa', 'panama'],
  ['Papua New Guinea', 'pg', 'papua-new-guinea'],
  ['Paraguay', 'py', 'paraguay'],
  ['Peru', 'pe', 'peru'],
  ['Philippines', 'ph', 'philippines'],
  ['Poland', 'pl', 'poland'],
  ['Portugal', 'pt', 'portugal'],
  ['Qatar', 'qa', 'qatar'],
  ['Romania', 'ro', 'romania'],
  ['Russia', 'ru', 'russia'],
  ['Rwanda', 'rw', 'rwanda'],
  ['Saint Kitts and Nevis', 'kn', 'saint-kitts-and-nevis'],
  ['Saint Lucia', 'lc', 'saint-lucia'],
  ['Saint Vincent and the Grenadines', 'vc', 'saint-vincent-and-the-grenadines'],
  ['Samoa', 'ws', 'samoa'],
  ['San Marino', 'sm', 'san-marino'],
  ['Sao Tome and Principe', 'st', 'sao-tome-and-principe'],
  ['Saudi Arabia', 'sa', 'saudi-arabia'],
  ['Senegal', 'sn', 'senegal'],
  ['Serbia', 'rs', 'serbia'],
  ['Seychelles', 'sc', 'seychelles'],
  ['Sierra Leone', 'sl', 'sierra-leone'],
  ['Singapore', 'sg', 'singapore'],
  ['Slovakia', 'sk', 'slovakia'],
  ['Slovenia', 'si', 'slovenia'],
  ['Solomon Islands', 'sb', 'solomon-islands'],
  ['Somalia', 'so', 'somalia'],
  ['South Africa', 'za', 'south-africa'],
  ['South Korea', 'kr', 'south-korea'],
  ['South Sudan', 'ss', 'south-sudan'],
  ['Spain', 'es', 'spain'],
  ['Sri Lanka', 'lk', 'sri-lanka'],
  ['Sudan', 'sd', 'sudan'],
  ['Suriname', 'sr', 'suriname'],
  ['Sweden', 'se', 'sweden'],
  ['Switzerland', 'ch', 'switzerland'],
  ['Syria', 'sy', 'syria'],
  ['Taiwan', 'tw', 'taiwan'],
  ['Tajikistan', 'tj', 'tajikistan'],
  ['Tanzania', 'tz', 'tanzania'],
  ['Thailand', 'th', 'thailand'],
  ['Timor-Leste', 'tl', 'timor-leste'],
  ['Togo', 'tg', 'togo'],
  ['Tonga', 'to', 'tonga'],
  ['Trinidad and Tobago', 'tt', 'trinidad-and-tobago'],
  ['Tunisia', 'tn', 'tunisia'],
  ['Turkey', 'tr', 'turkey'],
  ['Turkmenistan', 'tm', 'turkmenistan'],
  ['Tuvalu', 'tv', 'tuvalu'],
  ['Uganda', 'ug', 'uganda'],
  ['Ukraine', 'ua', 'ukraine'],
  ['United Arab Emirates', 'ae', 'united-arab-emirates'],
  ['United Kingdom', 'gb', 'united-kingdom'],
  ['United States', 'us', 'united-states'],
  ['Uruguay', 'uy', 'uruguay'],
  ['Uzbekistan', 'uz', 'uzbekistan'],
  ['Vanuatu', 'vu', 'vanuatu'],
  ['Vatican City', 'va', 'vatican-city'],
  ['Venezuela', 've', 'venezuela'],
  ['Vietnam', 'vn', 'vietnam'],
  ['Yemen', 'ye', 'yemen'],
  ['Zambia', 'zm', 'zambia'],
  ['Zimbabwe', 'zw', 'zimbabwe'],
].map(([name, code, slug]) => ({ name, code, slug }));

const bySlug = new Map(CANONICAL_COUNTRIES.map((country) => [country.slug, country]));
const byIso = new Map(CANONICAL_COUNTRIES.map((country) => [country.code.toLowerCase(), country]));

export function getCanonicalCountryBySlug(slug: string): CanonicalCountry | null {
  return bySlug.get(slug.trim().toLowerCase()) ?? null;
}

export function getCanonicalCountryByIso(code: string): CanonicalCountry | null {
  return byIso.get(code.trim().toLowerCase()) ?? null;
}

